### PR TITLE
Windows NT 3.1 support

### PR DESCRIPTION
**Pull request by davidrg**
Port C-Kermit for Windows to Windows NT 3.1 using Visual C++ 1.0 32-bit edition. Goal is to get it at least building and running - other bugs can be sorted out later.

- [x] k95g.exe does not work properly when built with Visual C++ 2.0 - window sizing / terminal sizing is messed up.
- [x] the orient command kills the app on NT 3.1 - possible GetShortPathName issue? Dies after getting the appdata path
- [x] Other console mode binaries (eg, k95d) aren't currently building due to WinAPI issues like GetVersionEx
- [x] Get X/Y/Z Modem building, or disable it if it can't be built
- [x] Get k95crypt building, or disable it if it can't be built
- [X] Confirm GetVersionEx is unavailable on NT 3.1, and not meerly unavailable in Visual C++ 1.0
- [x] Tidyup CKT_NT31 and CKT_NT35 checks. Currently CKT_NT35 just means Visual C++ 2.0 and there isn't any way to build for NT 3.50 that doesn't force building for the NT 3.1 API level.
- [x] Try to support as many NT 3.50 APIs as possible via GetProcAddress with fallbacks for NT 3.1 so that we can target NT 3.1 and NT 3.50 with Visual C++ 2.0 without losing features in NT 3.50
- [x] Check the new GetShortPathName implementation works properly
- [X] Check building for NT 3.1 with OpenWatcom - checked, doesn't work
- [X] Update supported compilers list

### CODE REVIEW

**Comment by davidrg** [comment]
The telnet issue (likely networking in general issue) appears to be in ckcnet.c, function netinc. The select call (guarded by `#ifdef BSDSELECT`) isn't working properly on Windows NT 3.1 for some unknown reason. It always appears to report ttyfd isn't ready to read (`rc == 0 && !FD_ISSET(ttyfd, &rfds)`) even when `ttchk()` (and its call to `socket_ioctl(ttyfd,FIONBIO,&y)`) reports there being bytes waiting to be read.

Given the FIONBIO ioctl has said there are bytes waiting to be read, the `select()` call _should_ be saying ttyfd is read to be read but it isn't. This is _only_ an issue on Windows NT 3.1 - this exact same code built with the same compiler works fine on other all other Windows versions. And if netinc is adjusted to ignore the select() result and instead try to read if ttchk() says there is data to be read, the problem goes away (and is replaced with another one - FIONBIO isn't very fast and apparently has the potential to be buggy).

I assume select() isn't outright broken on NT 3.1, its possible C-Kermit is just doing something that Windows NT 3.1 doesn't like. Just what that could be I have no idea at this time. Perhaps SO_OOBINLINE? Only out-of-band selects seem to be working - perhaps that's related. Or maybe some threading or timing issue? It doesn't always die at the exact same place so its not a matter of it breaking after receiving x bytes - sometimes it breaks immediately, sometimes it breaks after receiving a few screenfuls of data.

**Comment by brolin-empey** [comment]
Out of curiosity, on which generation of hardware or in which emulated or virtualised environment are you running Windows NT 3.x?  I have run Windows NT 3.1 on my own computer but it was in around 2002 and I think it was on an 80586-class computer so I do not know if NT 3.x runs on generations of hardware much newer than the OS, such as Athlon/Pentium 4 era or even Core 2 era or newer.  I am contactable at brolin@brolin.be if you prefer to reply via email.  Thank you for your commitment to the Kermit Project, no pun intended.

**Comment by davidrg** [comment]
When I was doing the NT 3.1 work I was using Oracle VirtualBox, though since upgrading my PC a few months ago my NT 3.1 VMs have been broken (CPU compatibility issues perhaps) so I'll probably switch to 86box in the future. Only real hardware I've run NT 3.1 on was a DEC Prioris LX 575 a few years ago - that machine chosen because it already had a SCSI CD-ROM drive installed. Sadly its PSU has developed a fault since then.

I think NT 3.5x still runs fine in VirtualBox, and NT4 runs well too with guest additions.

**Comment by davidrg** [comment]
Unfortunately the faulty PSU is something weird and non-standard. The power switch on the front is a low voltage one that is, IIRC, connected to the PSU via the motherboard so it's not using a regular AT power connector.

Eventually I'll probably try recapping and see if that makes it behave - if not I'll have to hope the service manual has a pinout for the PSU!

**Pull request merged**
